queue_BFS_tester: queue_BFS
	gcc -Wall --pedantic -ggdb queue_BFS_tester.c queue_BFS.c -o queue_BFS_tester.out
	rm *.o
queue_BFS: #maze_storage.c (bo Pole)
	gcc -Wall --pedantic -c queue_BFS.c
maze_storage:
	gcc -Wall --pedantic -c maze_storage.c